linters:
  enable:
    - revive  # 替代 golint
    - gofmt
    - goimports
    - govet
    - misspell
    - whitespace
    - gosimple
    - staticcheck
    - stylecheck

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/zcyberseclab/zasset

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint 