name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install libpcap
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest